template = "https://github.com/giellalt/template-lang-und"
rev_id = 288
template_sha = "dad1e9d42924a392d25de22e57436619ea3f5f1c"

[replacements]
__GLOTTOLOG_ID__ = "mund1330"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-myu"
__UND2C__ = "myu"
__UNDEFINED__ = "Mundurukú"
__UND__ = "myu"
