template = "https://github.com/giellalt/template-lang-und"
rev_id = 296
template_sha = "879b03783ce7c34cc6b4dfc240164614f484a26e"

[replacements]
__GLOTTOLOG_ID__ = "mund1330"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-myu"
__UND2C__ = "myu"
__UNDEFINED__ = "Mundurukú"
__UND__ = "myu"
