template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "mund1330"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-myu"
__UND2C__ = "myu"
__UNDEFINED__ = "Mundurukú"
__UND__ = "myu"
